/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_va_ndktaste_util_JniUtil */

#ifndef _Included_com_va_ndktaste_util_JniUtil
#define _Included_com_va_ndktaste_util_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_va_ndktaste_util_JniUtil
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_va_ndktaste_util_JniUtil_getName
  (JNIEnv *, jobject);

/*
 * Class:     com_va_ndktaste_util_JniUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_va_ndktaste_util_JniUtil_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
